pes = input("Digite algo: ")
ver =type(pes)
print('O tipo primitivo é', type(pes))
print('Só contem espaços? ', pes.isspace())
print('É um número? ', pes.isnumeric())
print('É um número inteiro? ', pes.isnumeric())
print('É um alfabético?? ', pes.isalpha())
print('É um caracter alfanumérico? ', pes.isalnum())
print('Esta em minusculo?', pes.islower())
print('Esta em maiusculo?', pes.isupper())
print('Esta captalizado?', pes.istitle())
